name: .NET Core

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: release
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore MattsTwitchBot.Web
    - name: Build
      run: dotnet build MattsTwitchBot.Web --configuration Release --no-restore
    - name: Test
      run: dotnet test MattsTwitchBot.Tests --no-restore --verbosity normal
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
        # Name of the Azure Web App
        app-name: MattsTwitchBot
        # Applies to Web App only: Publish profile (*.publishsettings) file contents with Web Deploy secrets
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: my-artifact
        # Directory containing files to upload
        path: /MattsTwitchBot.Web/appsettings.Developerment.json
