name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: release
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Test files?
      run: |
        ls .
        ls ./dbconfig
        cat ./dbconfig/buckets.json
    - name: Run CouchbaseFakeIt
      uses: brantburnett/run-couchbasefakeit@v0.1
      with:
        couchbase-version: enterprise-6.5.0
        couchbase-configuration: dbconfig
    - name: Install dependencies
      run: dotnet restore MattsTwitchBot.sln
    - name: Tests
      run: dotnet test MattsTwitchBot.Tests --verbosity normal
      env:
        COUCHBASE_CONNECTION_STRING: couchbase://localhost
        COUCHBASE_USERNAME: Administrator
        COUCHBASE_PASSWORD: password
        COUCHBASE_BUCKET_NAME: testbucket
